title: Planty
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/favicon.ico
logo_dark: images/logo.svg
logo_light: images/maroon-lavender.png
hamburger_background_image: /images/leaf-light-grey.svg
bg_image_primary: /images/header.jpg
bg_image_primary_opacity: 60
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: ''
footer_text: Copyright 2021 Planty Inc. All rights reserved.
palette: green
main_menu:
  - title: Home
    url: /store
    style: link
  - title: About
    url: /about
    style: link
  - title: Products & Services
    url: /faq
    style: link
  - title: lorem-ipsum
    url: lorem-ipsum
    style: primary
    arrow: false
    type: action
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
